telegrambots:
  bots:
    - name: BooklyBot
      username: BooklyBarbershopBot
      token: 8167055733:AAFAJIe7UPUVjj2q2YEEdbxQrRAuDTK9Ocg

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barberdb
    username: postgres
    password: 5117
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

yclients:
  partner-token: j8p3aadsnhaexg4wp8k9
  company-id: 86034
  user-token: c3e9471d9aea1ed8246ebf0c0f5b8305